# Testing Modules

## Testing Trainer Modules

In [1]:
import torch
from torch.utils.data import TensorDataset, DataLoader

from modules.architectures.Architecture import Architecture
from modules.helper.Trainer import Trainer

# Model
model = Architecture()
model.add(
    torch.nn.Linear(10, 1, bias=True)
).to("cuda")

# Dummy dataset
x_train = torch.randn(100, 10)   # 100 samples, 10 features
y_train = torch.randn(100, 1)    # 100 targets

x_test = torch.randn(100, 10)
y_test = torch.randn(100, 1)

# Dataset + DataLoader
train_dataset = TensorDataset(x_train, y_train)
test_dataset = TensorDataset(x_test, y_test)

train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=16)

# Optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=1e-3)

# Trainer
trainer = Trainer(
    model=model,
    train_loader=train_loader,
    val_loader=test_loader,
    optimizer=optimizer,
    criteration=torch.nn.MSELoss(),
    print_every=1,
    device="cuda"
)

metrics = trainer.train(100)

Epoch [1/100] | Train Loss: 1.0986 | Val Loss: 1.1374
Epoch [2/100] | Train Loss: 1.1560 | Val Loss: 1.1295
Epoch [3/100] | Train Loss: 1.2508 | Val Loss: 1.1213
Epoch [4/100] | Train Loss: 1.1894 | Val Loss: 1.1128
Epoch [5/100] | Train Loss: 1.0988 | Val Loss: 1.1051
Epoch [6/100] | Train Loss: 1.2643 | Val Loss: 1.0970
Epoch [7/100] | Train Loss: 1.1211 | Val Loss: 1.0868
Epoch [8/100] | Train Loss: 1.0132 | Val Loss: 1.0806
Epoch [9/100] | Train Loss: 1.1678 | Val Loss: 1.0746
Epoch [10/100] | Train Loss: 0.9984 | Val Loss: 1.0682
Epoch [11/100] | Train Loss: 1.1331 | Val Loss: 1.0614
Epoch [12/100] | Train Loss: 1.0674 | Val Loss: 1.0561
Epoch [13/100] | Train Loss: 1.1704 | Val Loss: 1.0464
Epoch [14/100] | Train Loss: 1.0767 | Val Loss: 1.0396
Epoch [15/100] | Train Loss: 1.0154 | Val Loss: 1.0318
Epoch [16/100] | Train Loss: 0.9984 | Val Loss: 1.0260
Epoch [17/100] | Train Loss: 1.1631 | Val Loss: 1.0197
Epoch [18/100] | Train Loss: 0.9990 | Val Loss: 1.0157
Epoch [19/100] | Train Loss: 1.0661 | Val Loss: 1.0118
Epoch [20/100] | Train Loss: 1.1638 | Val Loss: 1.0080
Epoch [21/100] | Train Loss: 0.9084 | Val Loss: 1.0047
Epoch [22/100] | Train Loss: 1.1646 | Val Loss: 0.9999
Epoch [23/100] | Train Loss: 1.0414 | Val Loss: 0.9963
Epoch [24/100] | Train Loss: 0.8983 | Val Loss: 0.9927
Epoch [25/100] | Train Loss: 0.9169 | Val Loss: 0.9886
Epoch [26/100] | Train Loss: 0.8939 | Val Loss: 0.9847
Epoch [27/100] | Train Loss: 0.9040 | Val Loss: 0.9814
Epoch [28/100] | Train Loss: 1.0128 | Val Loss: 0.9790
Epoch [29/100] | Train Loss: 0.8871 | Val Loss: 0.9753
Epoch [30/100] | Train Loss: 0.8623 | Val Loss: 0.9720
Epoch [31/100] | Train Loss: 0.8614 | Val Loss: 0.9698
Epoch [32/100] | Train Loss: 0.8640 | Val Loss: 0.9671
Epoch [33/100] | Train Loss: 0.9398 | Val Loss: 0.9636
Epoch [34/100] | Train Loss: 0.9827 | Val Loss: 0.9594
Epoch [35/100] | Train Loss: 0.8265 | Val Loss: 0.9572
Epoch [36/100] | Train Loss: 0.8755 | Val Loss: 0.9551
Epoch [37/100] | Train Loss: 0.9394 | Val Loss: 0.9540
Epoch [38/100] | Train Loss: 0.8589 | Val Loss: 0.9518
Epoch [39/100] | Train Loss: 0.9036 | Val Loss: 0.9498
Epoch [40/100] | Train Loss: 0.8584 | Val Loss: 0.9475
Epoch [41/100] | Train Loss: 0.8202 | Val Loss: 0.9454
Epoch [42/100] | Train Loss: 0.9370 | Val Loss: 0.9444
Epoch [43/100] | Train Loss: 0.9721 | Val Loss: 0.9415
Epoch [44/100] | Train Loss: 0.9233 | Val Loss: 0.9388
Epoch [45/100] | Train Loss: 0.7919 | Val Loss: 0.9374
Epoch [46/100] | Train Loss: 0.9790 | Val Loss: 0.9324
Epoch [47/100] | Train Loss: 0.7975 | Val Loss: 0.9320
Epoch [48/100] | Train Loss: 0.8164 | Val Loss: 0.9296
Epoch [49/100] | Train Loss: 0.9003 | Val Loss: 0.9271
Epoch [50/100] | Train Loss: 0.8810 | Val Loss: 0.9257
Epoch [51/100] | Train Loss: 0.8078 | Val Loss: 0.9250
Epoch [52/100] | Train Loss: 0.7765 | Val Loss: 0.9241
Epoch [53/100] | Train Loss: 0.7998 | Val Loss: 0.9225
Epoch [54/100] | Train Loss: 0.7859 | Val Loss: 0.9213
Epoch [55/100] | Train Loss: 0.8321 | Val Loss: 0.9211
Epoch [56/100] | Train Loss: 0.8293 | Val Loss: 0.9206
Epoch [57/100] | Train Loss: 0.7948 | Val Loss: 0.9193
Epoch [58/100] | Train Loss: 0.7793 | Val Loss: 0.9190
Epoch [59/100] | Train Loss: 0.8674 | Val Loss: 0.9176
Epoch [60/100] | Train Loss: 0.7937 | Val Loss: 0.9163
Epoch [61/100] | Train Loss: 0.7917 | Val Loss: 0.9165
Epoch [62/100] | Train Loss: 0.7614 | Val Loss: 0.9165
Epoch [63/100] | Train Loss: 0.8665 | Val Loss: 0.9147
Epoch [64/100] | Train Loss: 0.9468 | Val Loss: 0.9139
Epoch [65/100] | Train Loss: 0.7828 | Val Loss: 0.9128
Epoch [66/100] | Train Loss: 0.8132 | Val Loss: 0.9125
Epoch [67/100] | Train Loss: 0.7517 | Val Loss: 0.9120
Epoch [68/100] | Train Loss: 0.8418 | Val Loss: 0.9111
Epoch [69/100] | Train Loss: 0.8569 | Val Loss: 0.9100
Epoch [70/100] | Train Loss: 0.8475 | Val Loss: 0.9095
Epoch [71/100] | Train Loss: 0.8011 | Val Loss: 0.9083
Epoch [72/100] | Train Loss: 0.8323 | Val Loss: 0.9093
Epoch [73/100] | Train Loss: 0.7748 | Val Loss: 0.9084
Epoch [74/100] | Train Loss: 0.7339 | Val Loss: 0.9085
Epoch [75/100] | Train Loss: 0.9307 | Val Loss: 0.9077
Epoch [76/100] | Train Loss: 0.8085 | Val Loss: 0.9084
Epoch [77/100] | Train Loss: 0.7563 | Val Loss: 0.9090
Epoch [78/100] | Train Loss: 0.7382 | Val Loss: 0.9089
Epoch [79/100] | Train Loss: 0.8433 | Val Loss: 0.9100
Epoch [80/100] | Train Loss: 0.7614 | Val Loss: 0.9087
Epoch [81/100] | Train Loss: 0.8135 | Val Loss: 0.9089
Epoch [82/100] | Train Loss: 0.8610 | Val Loss: 0.9075
Epoch [83/100] | Train Loss: 0.8590 | Val Loss: 0.9062
Epoch [84/100] | Train Loss: 0.8133 | Val Loss: 0.9078
Epoch [85/100] | Train Loss: 0.8223 | Val Loss: 0.9067
Epoch [86/100] | Train Loss: 0.8184 | Val Loss: 0.9079
Epoch [87/100] | Train Loss: 0.8300 | Val Loss: 0.9082
Epoch [88/100] | Train Loss: 0.7470 | Val Loss: 0.9078
Epoch [89/100] | Train Loss: 0.7941 | Val Loss: 0.9078
Epoch [90/100] | Train Loss: 0.7391 | Val Loss: 0.9077
Epoch [91/100] | Train Loss: 0.7123 | Val Loss: 0.9077
Epoch [92/100] | Train Loss: 0.7858 | Val Loss: 0.9086
Epoch [93/100] | Train Loss: 0.8067 | Val Loss: 0.9088
Epoch [94/100] | Train Loss: 0.7746 | Val Loss: 0.9081
Epoch [95/100] | Train Loss: 0.8490 | Val Loss: 0.9099
Epoch [96/100] | Train Loss: 0.7256 | Val Loss: 0.9097
Epoch [97/100] | Train Loss: 0.8333 | Val Loss: 0.9096
Epoch [98/100] | Train Loss: 0.7447 | Val Loss: 0.9090
Epoch [99/100] | Train Loss: 0.8374 | Val Loss: 0.9088
Epoch [100/100] | Train Loss: 0.7127 | Val Loss: 0.9089

In [2]:
import pandas as pd

new_metrics_pd = pd.DataFrame(metrics)
new_metrics_pd.head()

,epoch,train_loss,val_loss,train_accuracy,train_precision,train_recall,train_f1-score,train_per_class_metrics,train_confusion_matrix,val_accuracy,val_precision,val_recall,val_f1-score,val_per_class_metrics,val_confusion_matrix
0,1,1.098588,1.137403,0.0,0.0,0.0,0.0,"{-1.845057725906372: {'Precision': 0, 'Recall'...",-1.845058 -1.840198 -1.813086 -1...,0.0,0.0,0.0,0.0,"{-2.563054323196411: {'Precision': 0, 'Recall'...",-2.563054 -1.873684 -1.814003 -1...
1,2,1.155972,1.129454,0.0,0.0,0.0,0.0,"{-1.845057725906372: {'Precision': 0, 'Recall'...",-1.845058 -1.840198 -1.813086 -1...,0.0,0.0,0.0,0.0,"{-2.563054323196411: {'Precision': 0, 'Recall'...",-2.563054 -1.873684 -1.814003 -1...
2,3,1.250769,1.121348,0.0,0.0,0.0,0.0,"{-1.845057725906372: {'Precision': 0, 'Recall'...",-1.845058 -1.840198 -1.813086 -1...,0.0,0.0,0.0,0.0,"{-2.563054323196411: {'Precision': 0, 'Recall'...",-2.563054 -1.873684 -1.814003 -1...
3,4,1.189441,1.112813,0.0,0.0,0.0,0.0,"{-1.845057725906372: {'Precision': 0, 'Recall'...",-1.845058 -1.840198 -1.813086 -1...,0.0,0.0,0.0,0.0,"{-2.563054323196411: {'Precision': 0, 'Recall'...",-2.563054 -1.873684 -1.814003 -1...
4,5,1.098786,1.105054,0.0,0.0,0.0,0.0,"{-1.845057725906372: {'Precision': 0, 'Recall'...",-1.845058 -1.840198 -1.813086 -1...,0.0,0.0,0.0,0.0,"{-2.563054323196411: {'Precision': 0, 'Recall'...",-2.563054 -1.873684 -1.814003 -1...

In [3]:
new_metrics_pd.iloc[0]["val_confusion_matrix"]

,-2.563054,-1.873684,-1.814003,-1.613137,-1.530311,-1.485098,-1.351828,-1.257911,-1.238637,-1.080140,...,1.371685,1.394310,1.423006,1.509986,1.592352,1.652866,1.663249,1.676274,2.071810,2.223675
-2.563054,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
-1.873684,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
-1.814003,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
-1.613137,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
-1.530311,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1.652866,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1.663249,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1.676274,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2.071810,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2.223675,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0